spring:
  config:
    activate:
      on-profile: kafka

  # Kafka Configurations.
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      bootstrap-servers: ${KAFKA_SERVER}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${KAFKA_GROUP_ID}
      properties:
        spring:
          json:
            trusted:
              packages: in.ayush.swasthyapath.kafka.model

    topic:
      name: doctor-consulted