spring:
  application:
    name: SwasthyaPath
  data:
    mongodb:
      uri: ${MONGO_URI}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: false

  # ACTIVE PROFILE
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}

  # Mail configuration.
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com

server:
  port: 8080

# Frontend origin.
frontend:
  origin: ${FRONTEND_ORIGIN}

# JWT config.
jwt:
  secret:
    key: ${JWT_SECRET}

# API Config for using the supabase s3 bucket.
supabase:
  api:
    url: ${SUPABASE_URL}
    serviceKey: ${SUPABASE_SERVICE_KEY}

perplexity:
  ai:
    api:
      key: ${PERPLEXITY_API_KEY}
      base-url: ${PERPLEXITY_BASE_URL}
      model: sonar
      completions-path: ${PERPLEXITY_COMPLETIONS_PATH}